version: "3.7"
services:
  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_EXPOSED_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,PLAINTEXT_HOST://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - ${KAFKA_EXPOSED_PORT}:9092
  transaction:
    build:
      context: ./packages/transaction
      dockerfile: Dockerfile
    env_file:
      - ./packages/transaction/.env
    ports:
      - ${MS_TRANSACTION_EXPOSED_PORT}:3000
    expose:
      - ${MS_TRANSACTION_EXPOSED_PORT}
    depends_on:
      - kafka
      - postgres
  antifraud:
    build:
      context: ./packages/anti-fraud
      dockerfile: Dockerfile
    env_file:
      - ./packages/anti-fraud/.env
    depends_on:
      - kafka
